### ISSUE TITLE
 importance of motifs for specific classes

### ISSUE THREAD

**Issue by Delasa** [davek44/Basset#36]
Hello,
How can we assess the importance of motifs for specific classes? In the paper, you discuss that Basset is able to pull out motifs specific to cell types. However, when we look at the filters and their motifs, there is no way to tell which motifs are important for which classes specially in a multi-class problem.

**Comment by davek44** [comment]
If you're interested in the filters themselves, you can try the script basset_motifs_infl.py, which will nullify the variance through that filter and measure how the predictions change. That's how I made Figure 3A (http://genome.cshlp.org/content/26/7/990/F3.expansion.html). However, it can be difficult to interpret because some motifs are captured by many filters.

basset_db.py might be a more useful analysis. In that script, I inject instances of known motifs from a database like CIS-BP into random sequences and measure how predictions change. The results there usually fit better with known relationships, e.g. OCT4 motifs and pluripotent cells.
